---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
discovery.type: single-node

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.authc.token.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.ssl.key: /usr/share/elasticsearch/config/client.key
xpack.ssl.certificate: /usr/share/elasticsearch/config/client.crt
xpack.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca.crt

xpack.security.authc.realms.saml1:
  type: saml
  order: 2
  idp.metadata.path: kibana-saml-idp.xml
  idp.entity_id: "https://keycloak:8443/auth/realms/Demo"
  sp.entity_id:  "kibana-saml"
  sp.acs: "https://kibana:5601/api/security/v1/saml"
  sp.logout: "https://kibana:5601/logout"
  attributes.principal: "urn:oid:0.9.2342.19200300.100.1.1"
  attributes.groups: "urn:oid:1.3.6.1.4.1.5923.1.5.1."
