version: '3'

services:
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ch4ng3m3!
    ports:
    - "443:8443"
    networks:
    - keycloak

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 6.4.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
      ELASTIC_PASSWORD: ch4ng3m3!
    networks:
      - keycloak

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 6.4.0
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - keycloak
    depends_on:
      - elasticsearch

  elasticsearch-data:
    build:
      context: elasticsearch-data/
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: ch4ng3m3!
    networks:
      - keycloak
    depends_on:
      - elasticsearch
      - kibana

  oidc-expressjs:
    build:
      context: oidc-expressjs/
    ports:
    - "3000:3000"
    networks:
    - keycloak

networks:
  keycloak:
    driver: bridge
